version: '3.8'

services:
  petition_db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: petition_user
      POSTGRES_PASSWORD: welcome@123
      POSTGRES_DB: petition_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  petition_api:
    build: ./api
    environment:
      DATABASE_URI: 'postgresql://petition_user:welcome@123@postgres/petition_db'
    ports:
      - '5001:5000'
    depends_on:
      - petition_db
  petition_bot:
    build: ./bot
    environment:
      TOKEN: 'MTA5OTIzMDI1MTkyMzU0NjIwMg.GYceqz.1isHjZp1m97_J_-ipsvCBQ9VvGxq9Dy150j0zc'
      API_URL: 'http://api:5001'
    depends_on:
      - petition_api

volumes:
  pg_data:
