CREATE DATABASE discord_bot;
CREATE USER yann WITH PASSWORD 'password';
CREATE USER kevin WITH PASSWORD 'password';
CREATE USER nhan WITH PASSWORD 'password';
CREATE USER querido WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE petitions TO yann;
GRANT ALL PRIVILEGES ON DATABASE petitions TO kevin;
GRANT ALL PRIVILEGES ON DATABASE petitions TO nhan;
GRANT ALL PRIVILEGES ON DATABASE petitions TO querido;